# Generated by Django 5.1.15 on 2026-04-06 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('rsvp_status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('waitlisted', 'Waitlisted')], default='accepted', max_length=20)),
                ('dietary_preferences', models.TextField(blank=True, default='')),
                ('plus_one_name', models.CharField(blank=True, default='', max_length=255)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('checked_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'email'), name='unique_guest_per_event')],
            },
        ),
    ]
